// MAJ Portfolio — projects data
// Each project has an original abstract monogram (SVG) and an
// atmospheric layered gradient as a placeholder for architectural
// renderings. Bilingual EN/AR.

window.MAJ_PORTFOLIO = [
  {
    id: "p01",
    title: "Folded Horizon Tower",
    ar: "برج الأفق المطوي",
    loc: "Doha · Qatar",
    locAr: "الدوحة، قطر",
    year: "2024–2027",
    type: "Mixed-use",
    area: "182,000 m²",
    status: "On site",
    desc: "A tower that folds its silhouette toward the bay, opening a continuous public terrace at every fifth floor. The structural diagrid is expressed as a soft fold in the facade rather than a sharp edge — what we call a 'tectonic crease'.",
    descAr: "برج يطوي صورته الظلية نحو الخليج، فاتحاً شرفة عامة متصلة كل خمسة طوابق. تتجلى الشبكة الإنشائية كثنية ناعمة في الواجهة بدل أن تكون حافة حادة.",
    // 4 frames (alt views)
    frames: [
      "linear-gradient(170deg, #c2cdd6 0%, #8a98a8 30%, #4a5566 65%, #1f242c 100%)",
      "linear-gradient(180deg, #d9c8a6 0%, #b39668 40%, #6b513a 80%, #2a1f17 100%)",
      "linear-gradient(200deg, #1f2a36 0%, #3d5470 50%, #cc9358 90%)",
      "linear-gradient(180deg, #e6dcc8 0%, #b8a17a 100%)",
    ],
    mono: "folded",
  },
  {
    id: "p02",
    title: "Saline Reserve",
    ar: "محمية الملاحات",
    loc: "AlUla · KSA",
    locAr: "العُلا، السعودية",
    year: "2025–2026",
    type: "Hospitality",
    area: "21,400 m²",
    status: "In construction",
    desc: "Three rammed-earth pavilions sit on a dry salt flat. Each is oriented to a different cardinal feature: an escarpment, an oasis, and a road of fossils. The roofs float on a thin steel datum that catches the western light.",
    descAr: "ثلاثة أجنحة من الطين المدكوك على سهل ملحي جاف. كل جناح موجَّه نحو معلم رئيسي: جرف، واحة، وطريق متحجرات. تطفو الأسقف على خط فولاذي رفيع يلتقط ضوء الغرب.",
    frames: [
      "linear-gradient(180deg, #f0d9b0 0%, #c79e6c 40%, #7a5a3a 75%, #2d2018 100%)",
      "linear-gradient(180deg, #ddd3c2 0%, #a89876 50%, #3d3528 100%)",
      "linear-gradient(190deg, #2c2419 0%, #8a6940 50%, #e0c290 100%)",
      "linear-gradient(180deg, #1a1714 0%, #4a3d2e 100%)",
    ],
    mono: "saline",
  },
  {
    id: "p03",
    title: "Stratum Library",
    ar: "مكتبة الطبقات",
    loc: "Muscat · Oman",
    locAr: "مسقط، عُمان",
    year: "2023",
    type: "Cultural",
    area: "9,800 m²",
    status: "Built",
    desc: "A library built into the side of a wadi, its stacks expressed as horizontal stone strata. Reading rooms cantilever toward the sea; service stairs and shafts are pulled to the inland edge to leave the seaward facade clear.",
    descAr: "مكتبة مبنية في جانب وادٍ، تتجلى رفوفها كطبقات حجرية أفقية. تمتد قاعات القراءة نحو البحر كنتوءات؛ وتُسحب السلالم وخدماتها نحو الحافة الداخلية.",
    frames: [
      "linear-gradient(180deg, #d4c8b0 0%, #8e7f63 45%, #4a3d2c 100%)",
      "linear-gradient(170deg, #7b8a96 0%, #c1a479 100%)",
      "linear-gradient(180deg, #1a2530 0%, #3d5066 100%)",
      "linear-gradient(180deg, #ebdcc2 0%, #b89870 100%)",
    ],
    mono: "stratum",
  },
  {
    id: "p04",
    title: "Mirror Pavilion",
    ar: "جناح المرآة",
    loc: "Riyadh · KSA",
    locAr: "الرياض، السعودية",
    year: "2025",
    type: "Public · Cultural",
    area: "3,200 m²",
    status: "Built",
    desc: "A pavilion whose underside is fully mirrored, doubling the public garden it shelters. The structure disappears at noon and reappears at dusk as a slow horizontal sunset trapped in glass.",
    descAr: "جناح سطحه السفلي معكوس بالكامل، فيضاعف الحديقة العامة التي يأويها. تختفي البنية عند الظهيرة وتعود عند الغسق كغروب أفقي بطيء محبوس في الزجاج.",
    frames: [
      "linear-gradient(180deg, #e8e2d4 0%, #c2b89c 50%, #786a4a 100%)",
      "linear-gradient(180deg, #ffd9a3 0%, #d97c4a 50%, #3a1a14 100%)",
      "linear-gradient(180deg, #c0d4dd 0%, #5e7782 100%)",
      "linear-gradient(180deg, #ebe4d4 0%, #b8a982 100%)",
    ],
    mono: "mirror",
  },
  {
    id: "p05",
    title: "Dune Campus",
    ar: "حرم الكثبان",
    loc: "Sharjah · UAE",
    locAr: "الشارقة، الإمارات",
    year: "2024–2026",
    type: "Education",
    area: "64,500 m²",
    status: "On site",
    desc: "A university campus arranged as a slow ridge of habitable dunes. Programs are stacked beneath earth-toned shells; courtyards are pulled out of the mass as cool, planted voids.",
    descAr: "حرم جامعي يتشكل كسلسلة بطيئة من كثبان قابلة للسكن. البرامج مكدسة تحت قشور بألوان ترابية؛ والأفنية مسحوبة من الكتلة كفراغات باردة مزروعة.",
    frames: [
      "linear-gradient(180deg, #e5cfa0 0%, #b08a55 55%, #5a4226 100%)",
      "linear-gradient(180deg, #d9b682 0%, #8a6a3e 100%)",
      "linear-gradient(180deg, #2c1f12 0%, #b08545 100%)",
      "linear-gradient(180deg, #f0e0c0 0%, #b89868 100%)",
    ],
    mono: "dune",
  },
  {
    id: "p06",
    title: "Black Salt Mosque",
    ar: "مسجد الملح الأسود",
    loc: "Tabuk · KSA",
    locAr: "تبوك، السعودية",
    year: "2023",
    type: "Religious",
    area: "2,400 m²",
    status: "Built",
    desc: "A small mosque clad in black salt blocks quarried from the nearby flats. The qibla wall is a single uninterrupted slab; the rest of the room dissolves into a slow grid of light slots.",
    descAr: "مسجد صغير مكسوّ بكتل ملح أسود مستخرجة من السهول المجاورة. جدار القبلة لوح واحد متصل؛ وبقية القاعة تذوب في شبكة بطيئة من شقوق الضوء.",
    frames: [
      "linear-gradient(180deg, #2c2a26 0%, #0a0908 100%)",
      "linear-gradient(180deg, #1a1815 0%, #58504a 100%)",
      "linear-gradient(180deg, #3a3530 0%, #14110e 100%)",
      "linear-gradient(180deg, #2a261f 0%, #d4b884 100%)",
    ],
    mono: "salt",
  },
  {
    id: "p07",
    title: "Loop Terminal",
    ar: "محطة الحلقة",
    loc: "Manama · Bahrain",
    locAr: "المنامة، البحرين",
    year: "2026–2030",
    type: "Infrastructure",
    area: "118,000 m²",
    status: "In design",
    desc: "A passenger terminal designed as a single continuous concourse — arrivals on the lower loop, departures on the upper, joined at the ends by a slow climbing ramp wrapped in a perforated steel veil.",
    descAr: "محطة ركاب مصممة كصالة واحدة متصلة — الوصول في الحلقة السفلى، المغادرة في العليا، يربط طرفيهما منحدر صاعد ببطء مغلَّف بحجاب فولاذي مثقَّب.",
    frames: [
      "linear-gradient(180deg, #b8c3cc 0%, #6a7682 60%, #1e242a 100%)",
      "linear-gradient(180deg, #d8d2c4 0%, #786c58 100%)",
      "linear-gradient(180deg, #1a2024 0%, #4a5560 100%)",
      "linear-gradient(180deg, #c8b890 0%, #786648 100%)",
    ],
    mono: "loop",
  },
  {
    id: "p08",
    title: "Hollow Garden House",
    ar: "بيت الحديقة المجوف",
    loc: "Amman · Jordan",
    locAr: "عمان، الأردن",
    year: "2022",
    type: "Residential",
    area: "640 m²",
    status: "Built",
    desc: "A house arranged around a hollow garden core that drops the full height of the building. The living spaces look only inward; the perimeter is a thick service wall in raw concrete.",
    descAr: "منزل ينتظم حول قلب حديقي مجوف يهبط بكامل ارتفاع المبنى. تنظر الفراغات المعيشية إلى الداخل فقط؛ والمحيط جدار خدمي سميك من الخرسانة الخام.",
    frames: [
      "linear-gradient(180deg, #d8d4cc 0%, #908a80 50%, #383530 100%)",
      "linear-gradient(180deg, #b8c4a8 0%, #4a5840 100%)",
      "linear-gradient(180deg, #c4b89c 0%, #50443a 100%)",
      "linear-gradient(180deg, #1a1814 0%, #6a625a 100%)",
    ],
    mono: "hollow",
  },
];
